{% set name = "tinyrpc" %}
{% set version = "0.9.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 7fc67de35015bdddbd24ca71b16c147beb771091197d1b1e2cb4e9ab63ded661

build:
  number: 0
  script: "{{ PYTHON }} -m pip install --no-deps . -vv"
  noarch: python

requirements:
  host:
    - pip
    - python
    - six
    - wheel
  run:
    - python
    - six

test:
  imports:
    - tests
    - tinyrpc
    - tinyrpc.dispatch
    - tinyrpc.protocols
    - tinyrpc.server
    - tinyrpc.transports
  commands:
    - pip check

about:
  home: "https://github.com/mbr/tinyrpc"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "A small, modular, transport and protocol neutral RPC library that, among other things, supports JSON-RPC and zmq."
  doc_url: 
  dev_url: 

extra:
  anaconda-services:
   ref: https://anaconda.zendesk.com/agent/tickets/34583
  recipe-maintainers:
    - anaobi
